name: build release binaries for Mac

on:
  push:
    branches: [ "mac_release", "main" ]

jobs:
  build:
    name: Build project using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.SUBMODULE_TOKEN}}
          submodules: true
      - name: Build
        run: |
          sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'
          cmake . -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -G "Xcode" -DJUCE_BUILD_EXAMPLES=OFF -Bbuild_xcode
          xcodebuild -project build_xcode/juce-ci-test.xcodeproj -configuration Release -target ALL_BUILD
          mkdir juce-ci-test_release_mac
          cp build_xcode/src/AudioPluginExample_artefacts/Release/Standalone juce-ci-test_release_mac
          cp build_xcode/src/AudioPluginExample_artefacts/Release/AU juce-ci-test_release_mac
          cp build_xcode/src/AudioPluginExample_artefacts/Release/VST3 juce-ci-test_release_mac
      - name: save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: juce-ci-test_release_mac
          path: juce-ci-test_release_mac

