name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build project using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.SUBMODULE_TOKEN}}
          submodules: true
      - name: Build
        with:
          xcode-version: latest-stable
        run: |
          scripts/mac_build_release.sh
          
