name: build release binaries for Windows

on:
  push:
    branches: [ "win_release" ]

jobs:
  build:
    name: Build project using MSBuild command
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.SUBMODULE_TOKEN}}
          submodules: true
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: |
          cmake . -G "Visual Studio 17 2022" -A x64 -DJUCE_BUILD_EXAMPLES=OFF -Bbuild_msvs
          msbuild /m /p:Configuration=Release build_msvs/juce-ci-test.vcxproj
          mkdir juce-ci-test_release_win
          cp build_msvs/src/AudioPluginExample_artefacts/Release/Standalone juce-ci-test_release_win
          cp build_msvs/src/AudioPluginExample_artefacts/Release/VST3 juce-ci-test_release_win
      - name: save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: juce-ci-test_release_win
          path: juce-ci-test_release_win
